name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has had no activity in 180 days. Please comment if it is not actually stale'
        stale-issue-label: 'stale'
        days-before-stale: 180
        days-before-close: 7
        exempt-pr-label: 'no-stale'
        exempt-issue-label: 'no-stale'
